name: 'github-release-version'
description: 'Get the latest GitHub release version'
author: 'Svetlin Ralchev'

# Define your inputs here.
inputs:
  github-token:
    description: 'The GitHub token used to create an authenticated client'
    default: '${{ github.token }}'
    required: true

runs:
  using: node20
  main: dist/index.js
